### ISSUE TITLE
work with Arabic language

### ISSUE THREAD

**Issue by Mahmuod1** [clovaai/synthtiger#32]
how i can create dataset with Arabic language

**Comment by moonbings** [comment]
First you need to prepare Arabic corpus file and font files.
Put text file (.txt) in `resources/corpus` path and font files (.ttf) in `resources/font` path.

Next, run font preprocessing script.

```
python tools/extract_font_charset.py -w 4 resources/font
```

And then, you need to edit config file.
Change corpus file path to prepared corpus file path.
https://github.com/clovaai/synthtiger/blob/master/examples/synthtiger/config_horizontal.yaml#L14-L15

```yml
- paths: [resources/corpus/arabic.txt]
  weights: [1]
```

You can change other parameter values (e.g. `min_length: null`, `max_length: null`, `augmentation: 0`).

Finally, run this command to generate the Arabic dataset.

```bash
synthtiger -o results -w 4 -v examples/synthtiger/template.py SynthTiger examples/synthtiger/config_horizontal.yaml
```

---

**NOTE:**

`Arial` font is good for generating Arabic text images. But, other Arabic fonts may not be supported.
This problem is related to SynthTiger.

If you want to use other Arabic fonts now, you should change code as below (172, 196 line in `template.py`).
Note that if you change this code, you can't render curved text.

https://github.com/clovaai/synthtiger/blob/87f6de877d8497d3f3b14d414bd3b0ea5f017175/examples/synthtiger/template.py#L172

https://github.com/clovaai/synthtiger/blob/87f6de877d8497d3f3b14d414bd3b0ea5f017175/examples/synthtiger/template.py#L196

```python
# chars = utils.split_text(label, reorder=True)
chars = [label]
```

And then, run this command to generate the Arabic dataset.

```
python synthtiger -o results -w 4 -v examples/synthtiger/template.py SynthTiger examples/synthtiger/config_horizontal.yaml
```

**Comment by Mahmuod1** [comment]
thanks a lot for your fast replaying and your instructions
